// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: metrics/v1/ingest.proto

package metricsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsIngestor_Push_FullMethodName = "/metrics.v1.MetricsIngestor/Push"
)

// MetricsIngestorClient is the client API for MetricsIngestor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsIngestorClient interface {
	// Push starts a client-streaming RPC that ends with a summary response.
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricsBatch, PushResponse], error)
}

type metricsIngestorClient struct {
	cc grpc.ClientConnInterface
}

// NewMetricsIngestorClient creates a client for the MetricsIngestor service.
func NewMetricsIngestorClient(cc grpc.ClientConnInterface) MetricsIngestorClient {
	return &metricsIngestorClient{cc}
}

// Push starts the MetricsIngestor client streaming RPC.
func (c *metricsIngestorClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricsBatch, PushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsIngestor_ServiceDesc.Streams[0], MetricsIngestor_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricsBatch, PushResponse]{ClientStream: stream}
	return x, nil
}

// MetricsIngestor_PushClient is a backwards-compatible alias for the generic push client stream.
type MetricsIngestor_PushClient = grpc.ClientStreamingClient[MetricsBatch, PushResponse]

// MetricsIngestorServer is the server API for MetricsIngestor service.
// All implementations must embed UnimplementedMetricsIngestorServer
// for forward compatibility.
type MetricsIngestorServer interface {
	// Push handles a client-streaming RPC and returns a summary response.
	Push(grpc.ClientStreamingServer[MetricsBatch, PushResponse]) error
	mustEmbedUnimplementedMetricsIngestorServer()
}

// UnimplementedMetricsIngestorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsIngestorServer struct{}

// Push returns an unimplemented error for the MetricsIngestor service.
func (UnimplementedMetricsIngestorServer) Push(grpc.ClientStreamingServer[MetricsBatch, PushResponse]) error {
	return status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedMetricsIngestorServer) mustEmbedUnimplementedMetricsIngestorServer() {}
func (UnimplementedMetricsIngestorServer) testEmbeddedByValue()                         {}

// UnsafeMetricsIngestorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsIngestorServer will
// result in compilation errors.
type UnsafeMetricsIngestorServer interface {
	mustEmbedUnimplementedMetricsIngestorServer()
}

// RegisterMetricsIngestorServer registers the MetricsIngestor server with a gRPC registrar.
func RegisterMetricsIngestorServer(s grpc.ServiceRegistrar, srv MetricsIngestorServer) {
	// If the following call panics, it indicates UnimplementedMetricsIngestorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsIngestor_ServiceDesc, srv)
}

func _MetricsIngestor_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsIngestorServer).Push(&grpc.GenericServerStream[MetricsBatch, PushResponse]{ServerStream: stream})
}

// MetricsIngestor_PushServer is a backwards-compatible alias for the generic push server stream.
type MetricsIngestor_PushServer = grpc.ClientStreamingServer[MetricsBatch, PushResponse]

// MetricsIngestor_ServiceDesc is the grpc.ServiceDesc for MetricsIngestor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsIngestor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.v1.MetricsIngestor",
	HandlerType: (*MetricsIngestorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _MetricsIngestor_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metrics/v1/ingest.proto",
}
