// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: metrics/v1/ingest.proto

package metricsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IoOpType enumerates IO operation types for disk and RAID events.
type IoOpType int32

const (
	IoOpType_IO_OP_UNSPECIFIED IoOpType = 0
	IoOpType_IO_OP_READ        IoOpType = 1
	IoOpType_IO_OP_WRITE       IoOpType = 2
)

// Enum value maps for IoOpType.
var (
	IoOpType_name = map[int32]string{
		0: "IO_OP_UNSPECIFIED",
		1: "IO_OP_READ",
		2: "IO_OP_WRITE",
	}
	IoOpType_value = map[string]int32{
		"IO_OP_UNSPECIFIED": 0,
		"IO_OP_READ":        1,
		"IO_OP_WRITE":       2,
	}
)

// Enum returns a pointer to the enum value.
func (x IoOpType) Enum() *IoOpType {
	p := new(IoOpType)
	*p = x
	return p
}

// String returns the string representation of the value.
func (x IoOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

// Descriptor returns the protobuf descriptor.
func (IoOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_v1_ingest_proto_enumTypes[0].Descriptor()
}

// Type returns the enum type descriptor.
func (IoOpType) Type() protoreflect.EnumType {
	return &file_metrics_v1_ingest_proto_enumTypes[0]
}

// Number returns the enum value as a protoreflect number.
func (x IoOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// EnumDescriptor returns the legacy enum descriptor. Deprecated: Use IoOpType.Descriptor instead.
func (IoOpType) EnumDescriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{0}
}

// ----- FUSE -----
// FuseOpType enumerates FUSE operation types for filesystem events.
type FuseOpType int32

const (
	FuseOpType_FUSE_OP_UNSPECIFIED FuseOpType = 0
	FuseOpType_FUSE_OP_READ        FuseOpType = 1
	FuseOpType_FUSE_OP_WRITE       FuseOpType = 2
	FuseOpType_FUSE_OP_OPEN        FuseOpType = 3
	FuseOpType_FUSE_OP_FSYNC       FuseOpType = 4
)

// Enum value maps for FuseOpType.
var (
	FuseOpType_name = map[int32]string{
		0: "FUSE_OP_UNSPECIFIED",
		1: "FUSE_OP_READ",
		2: "FUSE_OP_WRITE",
		3: "FUSE_OP_OPEN",
		4: "FUSE_OP_FSYNC",
	}
	FuseOpType_value = map[string]int32{
		"FUSE_OP_UNSPECIFIED": 0,
		"FUSE_OP_READ":        1,
		"FUSE_OP_WRITE":       2,
		"FUSE_OP_OPEN":        3,
		"FUSE_OP_FSYNC":       4,
	}
)

// Enum returns a pointer to the enum value.
func (x FuseOpType) Enum() *FuseOpType {
	p := new(FuseOpType)
	*p = x
	return p
}

// String returns the string representation of the value.
func (x FuseOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

// Descriptor returns the protobuf descriptor.
func (FuseOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_v1_ingest_proto_enumTypes[1].Descriptor()
}

// Type returns the enum type descriptor.
func (FuseOpType) Type() protoreflect.EnumType {
	return &file_metrics_v1_ingest_proto_enumTypes[1]
}

// Number returns the enum value as a protoreflect number.
func (x FuseOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// EnumDescriptor returns the legacy enum descriptor. Deprecated: Use FuseOpType.Descriptor instead.
func (FuseOpType) EnumDescriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{1}
}

// MetricsBatch aggregates a batch of metrics sent by a client.
type MetricsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // np. "raid-simulator-1"
	SeqNo         uint64                 `protobuf:"varint,2,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`         // monotonic per source (pomaga debug/retry)
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // timestamp batch'a (opcjonalnie do walidacji)
	DiskOps       []*DiskOp              `protobuf:"bytes,10,rep,name=disk_ops,json=diskOps,proto3" json:"disk_ops,omitempty"`
	DiskStates    []*DiskState           `protobuf:"bytes,11,rep,name=disk_states,json=diskStates,proto3" json:"disk_states,omitempty"`
	RaidOps       []*RaidOp              `protobuf:"bytes,20,rep,name=raid_ops,json=raidOps,proto3" json:"raid_ops,omitempty"`
	RaidStates    []*RaidState           `protobuf:"bytes,21,rep,name=raid_states,json=raidStates,proto3" json:"raid_states,omitempty"`
	FuseOps       []*FuseOp              `protobuf:"bytes,30,rep,name=fuse_ops,json=fuseOps,proto3" json:"fuse_ops,omitempty"`
	Process       *ProcessSample         `protobuf:"bytes,40,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset resets the message to its zero value.
func (x *MetricsBatch) Reset() {
	*x = MetricsBatch{}
	mi := &file_metrics_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns the string representation of the value.
func (x *MetricsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks the type as a protobuf message.
func (*MetricsBatch) ProtoMessage() {}

// ProtoReflect returns the reflective view of the message.
func (x *MetricsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor returns the legacy message descriptor. Deprecated: Use MetricsBatch.ProtoReflect.Descriptor instead.
func (*MetricsBatch) Descriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{0}
}

// GetSourceId returns the SourceId field.
func (x *MetricsBatch) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

// GetSeqNo returns the SeqNo field.
func (x *MetricsBatch) GetSeqNo() uint64 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

// GetTimestamp returns the Timestamp field.
func (x *MetricsBatch) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetDiskOps returns the DiskOps field.
func (x *MetricsBatch) GetDiskOps() []*DiskOp {
	if x != nil {
		return x.DiskOps
	}
	return nil
}

// GetDiskStates returns the DiskStates field.
func (x *MetricsBatch) GetDiskStates() []*DiskState {
	if x != nil {
		return x.DiskStates
	}
	return nil
}

// GetRaidOps returns the RaidOps field.
func (x *MetricsBatch) GetRaidOps() []*RaidOp {
	if x != nil {
		return x.RaidOps
	}
	return nil
}

// GetRaidStates returns the RaidStates field.
func (x *MetricsBatch) GetRaidStates() []*RaidState {
	if x != nil {
		return x.RaidStates
	}
	return nil
}

// GetFuseOps returns the FuseOps field.
func (x *MetricsBatch) GetFuseOps() []*FuseOp {
	if x != nil {
		return x.FuseOps
	}
	return nil
}

// GetProcess returns the Process field.
func (x *MetricsBatch) GetProcess() *ProcessSample {
	if x != nil {
		return x.Process
	}
	return nil
}

// ----- DISK -----
// DiskOp represents a single disk IO operation sample.
type DiskOp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DiskId         string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`                           // label: disk_id
	Op             IoOpType               `protobuf:"varint,2,opt,name=op,proto3,enum=metrics.v1.IoOpType" json:"op,omitempty"`                       // READ/WRITE
	Bytes          uint64                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`                                          // licznik bajtów
	LatencySeconds float64                `protobuf:"fixed64,4,opt,name=latency_seconds,json=latencySeconds,proto3" json:"latency_seconds,omitempty"` // obserwacja do histogramu (>= 0)
	Error          bool                   `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`                                          // jeśli true => inkrementuj disk_errors
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

// Reset resets the message to its zero value.
func (x *DiskOp) Reset() {
	*x = DiskOp{}
	mi := &file_metrics_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns the string representation of the value.
func (x *DiskOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks the type as a protobuf message.
func (*DiskOp) ProtoMessage() {}

// ProtoReflect returns the reflective view of the message.
func (x *DiskOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor returns the legacy message descriptor. Deprecated: Use DiskOp.ProtoReflect.Descriptor instead.
func (*DiskOp) Descriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{1}
}

// GetDiskId returns the DiskId field.
func (x *DiskOp) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

// GetOp returns the Op field.
func (x *DiskOp) GetOp() IoOpType {
	if x != nil {
		return x.Op
	}
	return IoOpType_IO_OP_UNSPECIFIED
}

// GetBytes returns the Bytes field.
func (x *DiskOp) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

// GetLatencySeconds returns the LatencySeconds field.
func (x *DiskOp) GetLatencySeconds() float64 {
	if x != nil {
		return x.LatencySeconds
	}
	return 0
}

// GetError returns the Error field.
func (x *DiskOp) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

// DiskState captures a point-in-time disk state sample.
type DiskState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	QueueDepth    float64                `protobuf:"fixed64,2,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"` // gauge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset resets the message to its zero value.
func (x *DiskState) Reset() {
	*x = DiskState{}
	mi := &file_metrics_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns the string representation of the value.
func (x *DiskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks the type as a protobuf message.
func (*DiskState) ProtoMessage() {}

// ProtoReflect returns the reflective view of the message.
func (x *DiskState) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor returns the legacy message descriptor. Deprecated: Use DiskState.ProtoReflect.Descriptor instead.
func (*DiskState) Descriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{2}
}

// GetDiskId returns the DiskId field.
func (x *DiskState) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

// GetQueueDepth returns the QueueDepth field.
func (x *DiskState) GetQueueDepth() float64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

// ----- RAID -----
// RaidOp represents a single RAID IO operation sample.
type RaidOp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RaidId         string                 `protobuf:"bytes,1,opt,name=raid_id,json=raidId,proto3" json:"raid_id,omitempty"` // label: raid (np. "raid0", "raid1", "raid3")
	Op             IoOpType               `protobuf:"varint,2,opt,name=op,proto3,enum=metrics.v1.IoOpType" json:"op,omitempty"`
	Bytes          uint64                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	LatencySeconds float64                `protobuf:"fixed64,4,opt,name=latency_seconds,json=latencySeconds,proto3" json:"latency_seconds,omitempty"` // histogram
	Error          bool                   `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	// RAID1: jeśli READ został obsłużony przez konkretny dysk (do metryki raid1_reads_from_disk)
	ServedFromDiskId string `protobuf:"bytes,10,opt,name=served_from_disk_id,json=servedFromDiskId,proto3" json:"served_from_disk_id,omitempty"` // label: disk_id (tylko gdy ma sens)
	// RAID3: dodatkowe liczniki specyficzne dla parzystości / partial stripe
	Raid3ParityRead         bool `protobuf:"varint,20,opt,name=raid3_parity_read,json=raid3ParityRead,proto3" json:"raid3_parity_read,omitempty"`
	Raid3ParityWrite        bool `protobuf:"varint,21,opt,name=raid3_parity_write,json=raid3ParityWrite,proto3" json:"raid3_parity_write,omitempty"`
	Raid3PartialStripeWrite bool `protobuf:"varint,22,opt,name=raid3_partial_stripe_write,json=raid3PartialStripeWrite,proto3" json:"raid3_partial_stripe_write,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

// Reset resets the message to its zero value.
func (x *RaidOp) Reset() {
	*x = RaidOp{}
	mi := &file_metrics_v1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns the string representation of the value.
func (x *RaidOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks the type as a protobuf message.
func (*RaidOp) ProtoMessage() {}

// ProtoReflect returns the reflective view of the message.
func (x *RaidOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor returns the legacy message descriptor. Deprecated: Use RaidOp.ProtoReflect.Descriptor instead.
func (*RaidOp) Descriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{3}
}

// GetRaidId returns the RaidId field.
func (x *RaidOp) GetRaidId() string {
	if x != nil {
		return x.RaidId
	}
	return ""
}

// GetOp returns the Op field.
func (x *RaidOp) GetOp() IoOpType {
	if x != nil {
		return x.Op
	}
	return IoOpType_IO_OP_UNSPECIFIED
}

// GetBytes returns the Bytes field.
func (x *RaidOp) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

// GetLatencySeconds returns the LatencySeconds field.
func (x *RaidOp) GetLatencySeconds() float64 {
	if x != nil {
		return x.LatencySeconds
	}
	return 0
}

// GetError returns the Error field.
func (x *RaidOp) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

// GetServedFromDiskId returns the ServedFromDiskId field.
func (x *RaidOp) GetServedFromDiskId() string {
	if x != nil {
		return x.ServedFromDiskId
	}
	return ""
}

// GetRaid3ParityRead returns the Raid3ParityRead field.
func (x *RaidOp) GetRaid3ParityRead() bool {
	if x != nil {
		return x.Raid3ParityRead
	}
	return false
}

// GetRaid3ParityWrite returns the Raid3ParityWrite field.
func (x *RaidOp) GetRaid3ParityWrite() bool {
	if x != nil {
		return x.Raid3ParityWrite
	}
	return false
}

// GetRaid3PartialStripeWrite returns the Raid3PartialStripeWrite field.
func (x *RaidOp) GetRaid3PartialStripeWrite() bool {
	if x != nil {
		return x.Raid3PartialStripeWrite
	}
	return false
}

// RaidState captures a point-in-time RAID state sample.
type RaidState struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RaidId string                 `protobuf:"bytes,1,opt,name=raid_id,json=raidId,proto3" json:"raid_id,omitempty"`
	// RAID1
	Raid1ResyncProgress float64 `protobuf:"fixed64,10,opt,name=raid1_resync_progress,json=raid1ResyncProgress,proto3" json:"raid1_resync_progress,omitempty"` // 0..1 (gauge), jeśli nie dotyczy => pomiń (ustaw 0 albo nie wysyłaj)
	// Ogólne stany RAID
	Degraded          bool   `protobuf:"varint,20,opt,name=degraded,proto3" json:"degraded,omitempty"`                                              // gauge 0/1
	FailedDisks       uint32 `protobuf:"varint,21,opt,name=failed_disks,json=failedDisks,proto3" json:"failed_disks,omitempty"`                     // gauge (liczba)
	RebuildInProgress bool   `protobuf:"varint,22,opt,name=rebuild_in_progress,json=rebuildInProgress,proto3" json:"rebuild_in_progress,omitempty"` // gauge 0/1
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

// Reset resets the message to its zero value.
func (x *RaidState) Reset() {
	*x = RaidState{}
	mi := &file_metrics_v1_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns the string representation of the value.
func (x *RaidState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks the type as a protobuf message.
func (*RaidState) ProtoMessage() {}

// ProtoReflect returns the reflective view of the message.
func (x *RaidState) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor returns the legacy message descriptor. Deprecated: Use RaidState.ProtoReflect.Descriptor instead.
func (*RaidState) Descriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{4}
}

// GetRaidId returns the RaidId field.
func (x *RaidState) GetRaidId() string {
	if x != nil {
		return x.RaidId
	}
	return ""
}

// GetRaid1ResyncProgress returns the Raid1ResyncProgress field.
func (x *RaidState) GetRaid1ResyncProgress() float64 {
	if x != nil {
		return x.Raid1ResyncProgress
	}
	return 0
}

// GetDegraded returns the Degraded field.
func (x *RaidState) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

// GetFailedDisks returns the FailedDisks field.
func (x *RaidState) GetFailedDisks() uint32 {
	if x != nil {
		return x.FailedDisks
	}
	return 0
}

// GetRebuildInProgress returns the RebuildInProgress field.
func (x *RaidState) GetRebuildInProgress() bool {
	if x != nil {
		return x.RebuildInProgress
	}
	return false
}

// FuseOp represents a single FUSE operation sample.
type FuseOp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Op             FuseOpType             `protobuf:"varint,1,opt,name=op,proto3,enum=metrics.v1.FuseOpType" json:"op,omitempty"`
	Bytes          uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`                                          // dla READ/WRITE
	LatencySeconds float64                `protobuf:"fixed64,3,opt,name=latency_seconds,json=latencySeconds,proto3" json:"latency_seconds,omitempty"` // histogram dla READ/WRITE (>= 0)
	Error          bool                   `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

// Reset resets the message to its zero value.
func (x *FuseOp) Reset() {
	*x = FuseOp{}
	mi := &file_metrics_v1_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns the string representation of the value.
func (x *FuseOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks the type as a protobuf message.
func (*FuseOp) ProtoMessage() {}

// ProtoReflect returns the reflective view of the message.
func (x *FuseOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor returns the legacy message descriptor. Deprecated: Use FuseOp.ProtoReflect.Descriptor instead.
func (*FuseOp) Descriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{5}
}

// GetOp returns the Op field.
func (x *FuseOp) GetOp() FuseOpType {
	if x != nil {
		return x.Op
	}
	return FuseOpType_FUSE_OP_UNSPECIFIED
}

// GetBytes returns the Bytes field.
func (x *FuseOp) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

// GetLatencySeconds returns the LatencySeconds field.
func (x *FuseOp) GetLatencySeconds() float64 {
	if x != nil {
		return x.LatencySeconds
	}
	return 0
}

// GetError returns the Error field.
func (x *FuseOp) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

// ----- PROCESS -----
// ProcessSample records process-level metrics for the simulator.
type ProcessSample struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CpuSeconds          float64                `protobuf:"fixed64,1,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`                             // gauge
	ResidentMemoryBytes uint64                 `protobuf:"varint,2,opt,name=resident_memory_bytes,json=residentMemoryBytes,proto3" json:"resident_memory_bytes,omitempty"` // gauge
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

// Reset resets the message to its zero value.
func (x *ProcessSample) Reset() {
	*x = ProcessSample{}
	mi := &file_metrics_v1_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns the string representation of the value.
func (x *ProcessSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks the type as a protobuf message.
func (*ProcessSample) ProtoMessage() {}

// ProtoReflect returns the reflective view of the message.
func (x *ProcessSample) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor returns the legacy message descriptor. Deprecated: Use ProcessSample.ProtoReflect.Descriptor instead.
func (*ProcessSample) Descriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{6}
}

// GetCpuSeconds returns the CpuSeconds field.
func (x *ProcessSample) GetCpuSeconds() float64 {
	if x != nil {
		return x.CpuSeconds
	}
	return 0
}

// GetResidentMemoryBytes returns the ResidentMemoryBytes field.
func (x *ProcessSample) GetResidentMemoryBytes() uint64 {
	if x != nil {
		return x.ResidentMemoryBytes
	}
	return 0
}

// PushResponse summarizes the ingestion results for a streamed push.
type PushResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AcceptedBatches uint64                 `protobuf:"varint,1,opt,name=accepted_batches,json=acceptedBatches,proto3" json:"accepted_batches,omitempty"`
	AcceptedSamples uint64                 `protobuf:"varint,2,opt,name=accepted_samples,json=acceptedSamples,proto3" json:"accepted_samples,omitempty"`
	RejectedSamples uint64                 `protobuf:"varint,3,opt,name=rejected_samples,json=rejectedSamples,proto3" json:"rejected_samples,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Reset resets the message to its zero value.
func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_metrics_v1_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns the string representation of the value.
func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks the type as a protobuf message.
func (*PushResponse) ProtoMessage() {}

// ProtoReflect returns the reflective view of the message.
func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor returns the legacy message descriptor. Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_metrics_v1_ingest_proto_rawDescGZIP(), []int{7}
}

// GetAcceptedBatches returns the AcceptedBatches field.
func (x *PushResponse) GetAcceptedBatches() uint64 {
	if x != nil {
		return x.AcceptedBatches
	}
	return 0
}

// GetAcceptedSamples returns the AcceptedSamples field.
func (x *PushResponse) GetAcceptedSamples() uint64 {
	if x != nil {
		return x.AcceptedSamples
	}
	return 0
}

// GetRejectedSamples returns the RejectedSamples field.
func (x *PushResponse) GetRejectedSamples() uint64 {
	if x != nil {
		return x.RejectedSamples
	}
	return 0
}

var File_metrics_v1_ingest_proto protoreflect.FileDescriptor

const file_metrics_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x17metrics/v1/ingest.proto\x12\n" +
	"metrics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x03\n" +
	"\fMetricsBatch\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x15\n" +
	"\x06seq_no\x18\x02 \x01(\x04R\x05seqNo\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\bdisk_ops\x18\n" +
	" \x03(\v2\x12.metrics.v1.DiskOpR\adiskOps\x126\n" +
	"\vdisk_states\x18\v \x03(\v2\x15.metrics.v1.DiskStateR\n" +
	"diskStates\x12-\n" +
	"\braid_ops\x18\x14 \x03(\v2\x12.metrics.v1.RaidOpR\araidOps\x126\n" +
	"\vraid_states\x18\x15 \x03(\v2\x15.metrics.v1.RaidStateR\n" +
	"raidStates\x12-\n" +
	"\bfuse_ops\x18\x1e \x03(\v2\x12.metrics.v1.FuseOpR\afuseOps\x123\n" +
	"\aprocess\x18( \x01(\v2\x19.metrics.v1.ProcessSampleR\aprocess\"\x9c\x01\n" +
	"\x06DiskOp\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\x12$\n" +
	"\x02op\x18\x02 \x01(\x0e2\x14.metrics.v1.IoOpTypeR\x02op\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x04R\x05bytes\x12'\n" +
	"\x0flatency_seconds\x18\x04 \x01(\x01R\x0elatencySeconds\x12\x14\n" +
	"\x05error\x18\x05 \x01(\bR\x05error\"E\n" +
	"\tDiskState\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\x12\x1f\n" +
	"\vqueue_depth\x18\x02 \x01(\x01R\n" +
	"queueDepth\"\xe2\x02\n" +
	"\x06RaidOp\x12\x17\n" +
	"\araid_id\x18\x01 \x01(\tR\x06raidId\x12$\n" +
	"\x02op\x18\x02 \x01(\x0e2\x14.metrics.v1.IoOpTypeR\x02op\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x04R\x05bytes\x12'\n" +
	"\x0flatency_seconds\x18\x04 \x01(\x01R\x0elatencySeconds\x12\x14\n" +
	"\x05error\x18\x05 \x01(\bR\x05error\x12-\n" +
	"\x13served_from_disk_id\x18\n" +
	" \x01(\tR\x10servedFromDiskId\x12*\n" +
	"\x11raid3_parity_read\x18\x14 \x01(\bR\x0fraid3ParityRead\x12,\n" +
	"\x12raid3_parity_write\x18\x15 \x01(\bR\x10raid3ParityWrite\x12;\n" +
	"\x1araid3_partial_stripe_write\x18\x16 \x01(\bR\x17raid3PartialStripeWrite\"\xc7\x01\n" +
	"\tRaidState\x12\x17\n" +
	"\araid_id\x18\x01 \x01(\tR\x06raidId\x122\n" +
	"\x15raid1_resync_progress\x18\n" +
	" \x01(\x01R\x13raid1ResyncProgress\x12\x1a\n" +
	"\bdegraded\x18\x14 \x01(\bR\bdegraded\x12!\n" +
	"\ffailed_disks\x18\x15 \x01(\rR\vfailedDisks\x12.\n" +
	"\x13rebuild_in_progress\x18\x16 \x01(\bR\x11rebuildInProgress\"\x85\x01\n" +
	"\x06FuseOp\x12&\n" +
	"\x02op\x18\x01 \x01(\x0e2\x16.metrics.v1.FuseOpTypeR\x02op\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\x12'\n" +
	"\x0flatency_seconds\x18\x03 \x01(\x01R\x0elatencySeconds\x12\x14\n" +
	"\x05error\x18\x04 \x01(\bR\x05error\"d\n" +
	"\rProcessSample\x12\x1f\n" +
	"\vcpu_seconds\x18\x01 \x01(\x01R\n" +
	"cpuSeconds\x122\n" +
	"\x15resident_memory_bytes\x18\x02 \x01(\x04R\x13residentMemoryBytes\"\x8f\x01\n" +
	"\fPushResponse\x12)\n" +
	"\x10accepted_batches\x18\x01 \x01(\x04R\x0facceptedBatches\x12)\n" +
	"\x10accepted_samples\x18\x02 \x01(\x04R\x0facceptedSamples\x12)\n" +
	"\x10rejected_samples\x18\x03 \x01(\x04R\x0frejectedSamples*B\n" +
	"\bIoOpType\x12\x15\n" +
	"\x11IO_OP_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"IO_OP_READ\x10\x01\x12\x0f\n" +
	"\vIO_OP_WRITE\x10\x02*o\n" +
	"\n" +
	"FuseOpType\x12\x17\n" +
	"\x13FUSE_OP_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fFUSE_OP_READ\x10\x01\x12\x11\n" +
	"\rFUSE_OP_WRITE\x10\x02\x12\x10\n" +
	"\fFUSE_OP_OPEN\x10\x03\x12\x11\n" +
	"\rFUSE_OP_FSYNC\x10\x042O\n" +
	"\x0fMetricsIngestor\x12<\n" +
	"\x04Push\x12\x18.metrics.v1.MetricsBatch\x1a\x18.metrics.v1.PushResponse(\x01B2Z0metrics-gateway/internal/pb/metrics/v1;metricsv1b\x06proto3"

var (
	file_metrics_v1_ingest_proto_rawDescOnce sync.Once
	file_metrics_v1_ingest_proto_rawDescData []byte
)

func file_metrics_v1_ingest_proto_rawDescGZIP() []byte {
	file_metrics_v1_ingest_proto_rawDescOnce.Do(func() {
		file_metrics_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_v1_ingest_proto_rawDesc), len(file_metrics_v1_ingest_proto_rawDesc)))
	})
	return file_metrics_v1_ingest_proto_rawDescData
}

var file_metrics_v1_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_metrics_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_metrics_v1_ingest_proto_goTypes = []any{
	(IoOpType)(0),                 // 0: metrics.v1.IoOpType
	(FuseOpType)(0),               // 1: metrics.v1.FuseOpType
	(*MetricsBatch)(nil),          // 2: metrics.v1.MetricsBatch
	(*DiskOp)(nil),                // 3: metrics.v1.DiskOp
	(*DiskState)(nil),             // 4: metrics.v1.DiskState
	(*RaidOp)(nil),                // 5: metrics.v1.RaidOp
	(*RaidState)(nil),             // 6: metrics.v1.RaidState
	(*FuseOp)(nil),                // 7: metrics.v1.FuseOp
	(*ProcessSample)(nil),         // 8: metrics.v1.ProcessSample
	(*PushResponse)(nil),          // 9: metrics.v1.PushResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_metrics_v1_ingest_proto_depIdxs = []int32{
	10, // 0: metrics.v1.MetricsBatch.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 1: metrics.v1.MetricsBatch.disk_ops:type_name -> metrics.v1.DiskOp
	4,  // 2: metrics.v1.MetricsBatch.disk_states:type_name -> metrics.v1.DiskState
	5,  // 3: metrics.v1.MetricsBatch.raid_ops:type_name -> metrics.v1.RaidOp
	6,  // 4: metrics.v1.MetricsBatch.raid_states:type_name -> metrics.v1.RaidState
	7,  // 5: metrics.v1.MetricsBatch.fuse_ops:type_name -> metrics.v1.FuseOp
	8,  // 6: metrics.v1.MetricsBatch.process:type_name -> metrics.v1.ProcessSample
	0,  // 7: metrics.v1.DiskOp.op:type_name -> metrics.v1.IoOpType
	0,  // 8: metrics.v1.RaidOp.op:type_name -> metrics.v1.IoOpType
	1,  // 9: metrics.v1.FuseOp.op:type_name -> metrics.v1.FuseOpType
	2,  // 10: metrics.v1.MetricsIngestor.Push:input_type -> metrics.v1.MetricsBatch
	9,  // 11: metrics.v1.MetricsIngestor.Push:output_type -> metrics.v1.PushResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_metrics_v1_ingest_proto_init() }
func file_metrics_v1_ingest_proto_init() {
	if File_metrics_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_v1_ingest_proto_rawDesc), len(file_metrics_v1_ingest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_v1_ingest_proto_goTypes,
		DependencyIndexes: file_metrics_v1_ingest_proto_depIdxs,
		EnumInfos:         file_metrics_v1_ingest_proto_enumTypes,
		MessageInfos:      file_metrics_v1_ingest_proto_msgTypes,
	}.Build()
	File_metrics_v1_ingest_proto = out.File
	file_metrics_v1_ingest_proto_goTypes = nil
	file_metrics_v1_ingest_proto_depIdxs = nil
}
