stages:
  - bootstrap
  - lint
  - checks
  - quality
  - build & push
  - release

variables:
  GIT_STRATEGY: fetch
  GIT_FETCH_EXTRA_FLAGS: "--prune"
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: none
  GIT_CLEAN_FLAGS: none
  CARGO_TERM_COLOR: always
  CI_RUST_VERSION: "1.91"
  CI_RUST_IMAGE: "$CI_REGISTRY_IMAGE/ci:rust-$CI_RUST_VERSION"
  RUSTFLAGS: "-C debuginfo=2"

.rust-changes:
  rules:
    - changes:
        - "**/*.rs"
        - "**/build.rs"
        - "**/Cargo.toml"
        - "**/Cargo.lock"
        - "rust-toolchain*"
        - ".cargo/**/*"
        - "Dockerfile"
        - "Dockerfile.*"
        - "*/Dockerfile"
        - "docker/**/*"
        - ".gitlab-ci.yml"
        - ".gitlab/ci/**/*"
    - when: never


default:
  image: $CI_RUST_IMAGE
  tags:
    - primary
  interruptible: true
  before_script:
    - rustc --version
    - cargo --version
